name: Markdownlint

on:
  push:
    paths:
      - "**/*.md"
      - ".markdownlint.jsonc"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint.jsonc"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@94196ee1d15439c1b6651cd87ef14e88ec435966
        with:
          node-version: 20.x
      - name: Run Markdownlint
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          npm i -g markdownlint-cli2
          markdownlint-cli2 "**/*.md"